#!/bin/bash

# Перевірка на правильну кількість аргументів
if [ "$#" -ne 1 ]; then
    echo "Usage: kubectl stats <namespace>"
    exit 1
fi

NAMESPACE=$1

# Отримання статистики з реального кластеру
kubectl get pods -n "$NAMESPACE" --no-headers=true | while read -r line; do
    # Витягнення інформації про CPU та пам'ять з виводу
    NAME=$(echo "$line" | awk '{print $1}')
    CPU=$(echo "$line" | awk '{print $3}')
    MEMORY=$(echo "$line" | awk '{print $4}')

    # Виведення статистики у форматі "Resource, Namespace, Name, CPU, Memory"
    echo "Pod, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
